
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Genre
 *
 * Codename: genre
 * Id: a058d83a-5c5d-4290-9fcc-7a38786cefa9
 */
export const GenreValues = [
  "metal",
  "rock",
  "pop",
  "hip_hop",
  "folk",
  "experimental",
  "jazz",
  "all",
] as const;

/**
 * Type representing Genre taxonomy
 *
 * Codename: genre
 * Id: a058d83a-5c5d-4290-9fcc-7a38786cefa9
 */
export type Genre = (typeof GenreValues)[number];

/**
 * Type guard for Genre
 *
 * Codename: genre
 * Id: a058d83a-5c5d-4290-9fcc-7a38786cefa9
 */
export function isGenre(value: string | undefined | null): value is Genre {
  return (
    typeof value === "string" &&
    (GenreValues as readonly string[]).includes(value)
  );
}
