
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Importance
 *
 * Codename: importance
 * Id: 247e5720-8692-4eb2-839e-68b9de7cb059
 */
export const ImportanceValues = ["default", "important", "trivial"] as const;

/**
 * Type representing Importance taxonomy
 *
 * Codename: importance
 * Id: 247e5720-8692-4eb2-839e-68b9de7cb059
 */
export type Importance = (typeof ImportanceValues)[number];

/**
 * Type guard for Importance
 *
 * Codename: importance
 * Id: 247e5720-8692-4eb2-839e-68b9de7cb059
 */
export function isImportance(
  value: string | undefined | null,
): value is Importance {
  return (
    typeof value === "string" &&
    (ImportanceValues as readonly string[]).includes(value)
  );
}
