
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Month
 *
 * Codename: month
 * Id: 61f04fdf-d0d6-4277-a94c-0cc68a740e08
 */
export const MonthValues = [
  "january",
  "february",
  "march",
  "april",
  "may",
  "june",
  "july",
  "august",
  "september",
  "october",
  "november",
  "december",
] as const;

/**
 * Type representing Month taxonomy
 *
 * Codename: month
 * Id: 61f04fdf-d0d6-4277-a94c-0cc68a740e08
 */
export type Month = (typeof MonthValues)[number];

/**
 * Type guard for Month
 *
 * Codename: month
 * Id: 61f04fdf-d0d6-4277-a94c-0cc68a740e08
 */
export function isMonth(value: string | undefined | null): value is Month {
  return (
    typeof value === "string" &&
    (MonthValues as readonly string[]).includes(value)
  );
}
