
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Vocation
 *
 * Codename: vocation
 * Id: c2cd0726-d077-400e-be08-7621061d6107
 */
export const VocationValues = ["band_member", "author"] as const;

/**
 * Type representing Vocation taxonomy
 *
 * Codename: vocation
 * Id: c2cd0726-d077-400e-be08-7621061d6107
 */
export type Vocation = (typeof VocationValues)[number];

/**
 * Type guard for Vocation
 *
 * Codename: vocation
 * Id: c2cd0726-d077-400e-be08-7621061d6107
 */
export function isVocation(
  value: string | undefined | null,
): value is Vocation {
  return (
    typeof value === "string" &&
    (VocationValues as readonly string[]).includes(value)
  );
}
