
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Year
 *
 * Codename: year
 * Id: 58b7a826-77e3-45dc-988e-4b7ce9b54da3
 */
export const YearValues = ["n2024", "n2025", "n2026"] as const;

/**
 * Type representing Year taxonomy
 *
 * Codename: year
 * Id: 58b7a826-77e3-45dc-988e-4b7ce9b54da3
 */
export type Year = (typeof YearValues)[number];

/**
 * Type guard for Year
 *
 * Codename: year
 * Id: 58b7a826-77e3-45dc-988e-4b7ce9b54da3
 */
export function isYear(value: string | undefined | null): value is Year {
  return (
    typeof value === "string" &&
    (YearValues as readonly string[]).includes(value)
  );
}
