
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

/**
 * Type representing all languages
 */
export type LanguageCodenames =
  | "Austrailian"
  | "Chinese_(Traditional)"
  | "default"
  | "zh_cn"
  | "zh_Hant"
  | "zh-Hant";

/**
 * Type representing all content types
 */
export type ContentTypeCodenames =
  | "action"
  | "asset"
  | "band"
  | "callout"
  | "concert_review"
  | "concert"
  | "content_chunk"
  | "location"
  | "navigation_item"
  | "page"
  | "person"
  | "playlist_song"
  | "venue"
  | "visual_container"
  | "web_spotlight_root";

/**
 * Type representing all collections
 */
export type CollectionCodenames = "default" | "reviews";

/**
 * Type representing all workflows
 */
export type WorkflowCodenames = "default";

/**
 * Type representing all taxonomies
 */
export type TaxonomyCodenames =
  | "asset_type"
  | "genre"
  | "importance"
  | "month"
  | "vocation"
  | "year";

/**
 * Type representing all worksflow steps across all workflows
 */
export type WorkflowStepCodenames =
  | "archived"
  | "draft"
  | "published"
  | "scheduled";

/**
 * Type representing all element codenames across all content types
 */
export type ElementCodenames =
  | "alt_text"
  | "artist_name"
  | "asset_file"
  | "asset_title"
  | "asset_type"
  | "author"
  | "band_bio"
  | "band_genre"
  | "band_logo"
  | "band_member"
  | "band_name"
  | "band_playlist"
  | "band"
  | "city"
  | "concert"
  | "content"
  | "directions"
  | "event_date"
  | "first_name"
  | "headline"
  | "hero_image"
  | "image"
  | "items"
  | "last_name"
  | "lead_paragraph"
  | "location"
  | "metadata__meta_description"
  | "metadata__meta_keywords"
  | "metadata"
  | "promotional_image"
  | "reference__caption"
  | "reference__external_uri"
  | "reference__label"
  | "reference__untitled_linked_items"
  | "review_body"
  | "show_in_navigation"
  | "slug"
  | "social_media"
  | "song_link"
  | "song_title"
  | "state_province"
  | "street_address"
  | "subpages"
  | "subtitle"
  | "supporting_act__supporting_act"
  | "supporting_artist"
  | "telephone_number"
  | "ticket_purchasing"
  | "title"
  | "type"
  | "untitled_multiple_choice"
  | "untitled_rich_text"
  | "untitled_url_slug"
  | "url"
  | "venue_name"
  | "venue_slug"
  | "venue"
  | "vocation"
  | "zipcode";
