
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

import type { Elements, Snippet } from "@kontent-ai/delivery-sdk";

/**
 * metadata
 *
 * Id: 9d3bc921-60e0-460d-92a3-0bf34c6ad025
 * Codename: metadata
 */
export type Metadata = Snippet<
  MetadataElementCodenames,
  {
    /**
     * Meta Keywords
     *
     * Type: text
     * Required: false
     * Codename: metadata__meta_keywords
     * Id: 14ee3c2a-2fe6-421e-ae0e-a8a90d84fc73
     */
    readonly metadata__meta_keywords: Elements.TextElement;
    /**
     * Meta Description
     *
     * Type: text
     * Required: false
     * Codename: metadata__meta_description
     * Id: 85a8a109-a411-4ec5-bb89-36f3b0d73805
     */
    readonly metadata__meta_description: Elements.TextElement;
  }
>;

/**
 * Type representing all available element codenames for metadata
 */
export type MetadataElementCodenames =
  | "metadata__meta_keywords"
  | "metadata__meta_description";
