
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

import type { Elements, Snippet } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Reference
 *
 * Id: 5dce25de-3c88-4177-8c2c-6a0bfa70ee76
 * Codename: reference
 */
export type Reference = Snippet<
  ReferenceElementCodenames,
  {
    /**
     * Label
     *
     * Type: text
     * Required: false
     * Codename: reference__label
     * Id: b6f0a566-251c-4612-867e-522059754b5a
     */
    readonly reference__label: Elements.TextElement;
    /**
     * Caption
     *
     * Type: text
     * Required: false
     * Codename: reference__caption
     * Id: e4f36321-a0f2-492c-8570-963b2490de4a
     */
    readonly reference__caption: Elements.TextElement;
    /**
     * External URI
     *
     * Type: text
     * Required: false
     * Codename: reference__external_uri
     * Id: 55a37264-7e9d-4ead-ab03-643c0a1431ad
     */
    readonly reference__external_uri: Elements.TextElement;
    /**
     * Untitled linked items
     *
     * Type: modular_content
     * Required: false
     * Codename: reference__untitled_linked_items
     * Id: c0008386-9351-4e29-9211-69de00611271
     */
    readonly reference__untitled_linked_items: Elements.LinkedItemsElement<CoreContentType>;
  }
>;

/**
 * Type representing all available element codenames for Reference
 */
export type ReferenceElementCodenames =
  | "reference__label"
  | "reference__caption"
  | "reference__external_uri"
  | "reference__untitled_linked_items";
