
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

import type { Elements, Snippet } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Supporting Act
 *
 * Id: 010eab5c-341d-434f-9c5c-0d92330ebdc2
 * Codename: supporting_act
 */
export type SupportingAct = Snippet<
  SupportingActElementCodenames,
  {
    /**
     * Supporting Act
     *
     * Type: rich_text
     * Required: false
     * Codename: supporting_act__supporting_act
     * Id: 370b3625-fa97-48c2-9a44-52fe60140658
     * Guidelines: Include the name and short bio of the supporting act.
     */
    readonly supporting_act__supporting_act: Elements.RichTextElement<CoreContentType>;
  }
>;

/**
 * Type representing all available element codenames for Supporting Act
 */
export type SupportingActElementCodenames = "supporting_act__supporting_act";
