
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

export const assetFolders = {
  /**
   * bands
   */
  bands: {
    name: "bands",
    codename: "bands",
    id: "38ee124a-e44b-45e0-9b91-3be8a59d5c93",
    externalId: undefined,
    folders: {
      /**
       * damien jurado
       */
      damien_jurado: {
        name: "damien jurado",
        codename: "damien_jurado",
        id: "a172c676-4b94-47c5-98d3-63bcee4b14c9",
        externalId: undefined,
        folders: {},
      },

      /**
       * swervedriver
       */
      swervedriver: {
        name: "swervedriver",
        codename: "swervedriver",
        id: "d3c4d46a-2fd9-476f-be96-3c9973c05343",
        externalId: undefined,
        folders: {},
      },

      /**
       * failure
       */
      failure: {
        name: "failure",
        codename: "failure",
        id: "ddbbeabb-cdd9-4627-a3e8-dbb1dba63afc",
        externalId: undefined,
        folders: {},
      },

      /**
       * hum
       */
      hum: {
        name: "hum",
        codename: "hum",
        id: "2ff7545b-053a-40fe-9de3-4e0b5953e13b",
        externalId: undefined,
        folders: {},
      },
    },
  },
} as const;
