
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

export const collections = {
  /**
   * Reviews
   */
  reviews: {
    name: "Reviews",
    codename: "reviews",
    id: "0ff48180-c4b9-4e0e-9b20-4cc0d7a3f0c7",
  },

  /**
   * Default
   */
  default: {
    name: "Default",
    codename: "default",
    id: "00000000-0000-0000-0000-000000000000",
  },
} as const;
