
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

export const contentTypeSnippets = {
  /**
   * Supporting Act
   */
  supporting_act: {
    name: "Supporting Act",
    codename: "supporting_act",
    id: "010eab5c-341d-434f-9c5c-0d92330ebdc2",
    externalId: undefined,
    elements: {
      /**
       * Supporting Act (rich_text)
       * Guidelines: Include the name and short bio of the supporting act.
       */
      supporting_act__supporting_act: {
        name: "Supporting Act",
        codename: "supporting_act__supporting_act",
        id: "370b3625-fa97-48c2-9a44-52fe60140658",
        externalId: undefined,
        required: false,
        type: "rich_text",
      },
    },
  },

  /**
   * metadata
   */
  metadata: {
    name: "metadata",
    codename: "metadata",
    id: "9d3bc921-60e0-460d-92a3-0bf34c6ad025",
    externalId: undefined,
    elements: {
      /**
       * Meta Keywords (text)
       */
      metadata__meta_keywords: {
        name: "Meta Keywords",
        codename: "metadata__meta_keywords",
        id: "14ee3c2a-2fe6-421e-ae0e-a8a90d84fc73",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * Meta Description (text)
       */
      metadata__meta_description: {
        name: "Meta Description",
        codename: "metadata__meta_description",
        id: "85a8a109-a411-4ec5-bb89-36f3b0d73805",
        externalId: undefined,
        required: false,
        type: "text",
      },
    },
  },

  /**
   * Reference
   */
  reference: {
    name: "Reference",
    codename: "reference",
    id: "5dce25de-3c88-4177-8c2c-6a0bfa70ee76",
    externalId: undefined,
    elements: {
      /**
       * Label (text)
       */
      reference__label: {
        name: "Label",
        codename: "reference__label",
        id: "b6f0a566-251c-4612-867e-522059754b5a",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * Caption (text)
       */
      reference__caption: {
        name: "Caption",
        codename: "reference__caption",
        id: "e4f36321-a0f2-492c-8570-963b2490de4a",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * External URI (text)
       */
      reference__external_uri: {
        name: "External URI",
        codename: "reference__external_uri",
        id: "55a37264-7e9d-4ead-ab03-643c0a1431ad",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * Untitled linked items (modular_content)
       */
      reference__untitled_linked_items: {
        name: "Untitled linked items",
        codename: "reference__untitled_linked_items",
        id: "c0008386-9351-4e29-9211-69de00611271",
        externalId: undefined,
        required: false,
        type: "modular_content",
      },
    },
  },
} as const;
