
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

export const contentTypes = {
  /**
   * Venue
   */
  venue: {
    name: "Venue",
    codename: "venue",
    id: "fb0081ad-34a0-4c69-b262-7cec3bad6b4b",
    externalId: undefined,
    elements: {
      /**
       * Venue Name (text)
       * Guidelines: Name of the venue.
       */
      venue_name: {
        name: "Venue Name",
        codename: "venue_name",
        id: "dfb65a08-05dc-4415-9c44-07ff8e4f0118",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * Hero Image (asset)
       * Guidelines: Promotional image of the venue.
       */
      hero_image: {
        name: "Hero Image",
        codename: "hero_image",
        id: "86b003e1-5e49-4f93-aa1b-37af71880aab",
        externalId: undefined,
        required: false,
        type: "asset",
      },

      /**
       * Location (modular_content)
       * Guidelines: Full address and phone number of the venue.
       */
      location: {
        name: "Location",
        codename: "location",
        id: "6780fee5-6e72-4f75-adf5-a6ab08b45341",
        externalId: undefined,
        required: true,
        type: "modular_content",
      },

      /**
       * Venue Slug (url_slug)
       */
      venue_slug: {
        name: "Venue Slug",
        codename: "venue_slug",
        id: "d98b9243-e16f-4c54-a91b-49fcdb5c4dc4",
        externalId: undefined,
        required: true,
        type: "url_slug",
      },
    },
  },

  /**
   * Visual container
   */
  visual_container: {
    name: "Visual container",
    codename: "visual_container",
    id: "6c7119fc-b7ae-47d9-95c7-acf6dfa85ba7",
    externalId: undefined,
    elements: {
      /**
       * Title (text)
       */
      title: {
        name: "Title",
        codename: "title",
        id: "73f15933-6f48-4598-9eea-4897ef36d623",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * Subtitle (text)
       */
      subtitle: {
        name: "Subtitle",
        codename: "subtitle",
        id: "bec2069e-8acc-484e-9295-0f7dc561b98c",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * Items (modular_content)
       */
      items: {
        name: "Items",
        codename: "items",
        id: "9b27ba2c-6fdf-48e3-ba51-5044b0d915e1",
        externalId: undefined,
        required: false,
        type: "modular_content",
      },

      /**
       * Visual representation (multiple_choice)
       */
      untitled_multiple_choice: {
        name: "Visual representation",
        codename: "untitled_multiple_choice",
        id: "74a61915-f5c8-40bb-85bd-9d62971a6ebb",
        externalId: undefined,
        required: false,
        type: "multiple_choice",
        options: {
          /**
           * Grid
           */
          grid: {
            name: "Grid",
            id: "d1766f3e-bc80-44a9-99b4-5cbcd9ae32cb",
            codename: "grid",
            externalId: undefined,
          },

          /**
           * Stack
           */
          stack: {
            name: "Stack",
            id: "74fcdc9f-7b54-4f52-9dc1-f2475910f849",
            codename: "stack",
            externalId: undefined,
          },

          /**
           * Hero Unit
           */
          hero_unit: {
            name: "Hero Unit",
            id: "c24c3064-e35f-4c25-99e1-3a25c0c8fc1b",
            codename: "hero_unit",
            externalId: undefined,
          },
        },
      },
    },
  },

  /**
   * Concert
   */
  concert: {
    name: "Concert",
    codename: "concert",
    id: "7c2fab10-d233-4ba8-ba85-0aa99bc2fe05",
    externalId: undefined,
    elements: {
      /**
       * Title (text)
       * Guidelines: Write a short descriptive title for the concert including the name of the headliner.
       */
      title: {
        name: "Title",
        codename: "title",
        id: "03e61837-7fea-45d0-bb97-46286a779361",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * Band (text)
       */
      band: {
        name: "Band",
        codename: "band",
        id: "67f9a7aa-1a25-48d8-be03-6feff8ae8ed4",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * Event Date (date_time)
       * Guidelines: Use the date of the concert and the time doors open.
       */
      event_date: {
        name: "Event Date",
        codename: "event_date",
        id: "145bdfad-b39c-45b0-af8c-49f7066681e3",
        externalId: undefined,
        required: true,
        type: "date_time",
      },

      /**
       * Venue (modular_content)
       */
      venue: {
        name: "Venue",
        codename: "venue",
        id: "bd74db0e-8888-4192-8466-0131cc8bdfcb",
        externalId: undefined,
        required: true,
        type: "modular_content",
      },

      /**
       * Hero Image (asset)
       * Guidelines: Utilize the primary promotional image provided by the concert promoter, tour manager or, in the absence of these, an image from the headlining artist's press kit.
       */
      hero_image: {
        name: "Hero Image",
        codename: "hero_image",
        id: "43237b01-5d6d-436a-8aeb-3fe3d6d8e1c3",
        externalId: undefined,
        required: true,
        type: "asset",
      },

      /**
       * Lead Paragraph (rich_text)
       * Guidelines: Should include the name of the headliner(s), the name of the tour, and the record the tour is promoting.
       */
      lead_paragraph: {
        name: "Lead Paragraph",
        codename: "lead_paragraph",
        id: "39375c6d-b624-4fd9-af80-6f21985cb364",
        externalId: undefined,
        required: true,
        type: "rich_text",
      },

      /**
       * Body Text (rich_text)
       * Guidelines: Incorporate the most recent relevant portions of the band/artist's bio.
       */
      untitled_rich_text: {
        name: "Body Text",
        codename: "untitled_rich_text",
        id: "34536128-b406-4f53-84fd-8aeb53cd12f1",
        externalId: undefined,
        required: true,
        type: "rich_text",
      },

      /**
       * Supporting Artist (modular_content)
       * Guidelines: Link the support act for the concert if applicable.
       */
      supporting_artist: {
        name: "Supporting Artist",
        codename: "supporting_artist",
        id: "e87cda1f-8a3f-4d38-beb7-c016eef3fe0f",
        externalId: undefined,
        required: false,
        type: "modular_content",
      },

      /**
       * Ticket Purchasing (text)
       * Guidelines: Link to purchase tickets.
       */
      ticket_purchasing: {
        name: "Ticket Purchasing",
        codename: "ticket_purchasing",
        id: "4d703e1a-e8f2-4a95-a262-5f631955c803",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * slug (url_slug)
       */
      concert: {
        name: "slug",
        codename: "concert",
        id: "906246ed-68a3-462b-a05f-eef34d6369f3",
        externalId: undefined,
        required: true,
        type: "url_slug",
      },
    },
  },

  /**
   * Content Chunk
   */
  content_chunk: {
    name: "Content Chunk",
    codename: "content_chunk",
    id: "a797ce49-151e-4ecf-a12c-2a34ef9cd750",
    externalId: undefined,
    elements: {
      /**
       * Title (text)
       */
      title: {
        name: "Title",
        codename: "title",
        id: "3cf97a75-0941-4bba-ac68-ebbb50fe3ebb",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * Content (rich_text)
       */
      content: {
        name: "Content",
        codename: "content",
        id: "3bc4388e-c65f-4e2f-836a-aa5e55b1a350",
        externalId: undefined,
        required: true,
        type: "rich_text",
      },
    },
  },

  /**
   * Navigation item
   */
  navigation_item: {
    name: "Navigation item",
    codename: "navigation_item",
    id: "aab37be7-07b8-458a-afe5-855ec464c05a",
    externalId: undefined,
    elements: {
      /**
       * Title (text)
       */
      title: {
        name: "Title",
        codename: "title",
        id: "58147925-9553-4e01-a7a8-ce709482a952",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * Subpages (subpages)
       */
      subpages: {
        name: "Subpages",
        codename: "subpages",
        id: "05359978-9d45-4677-b632-3ca2ac41200d",
        externalId: undefined,
        required: false,
        type: "subpages",
      },

      /**
       * Content (modular_content)
       */
      content: {
        name: "Content",
        codename: "content",
        id: "600225f9-6560-47fd-8b81-1b004ef0da88",
        externalId: undefined,
        required: false,
        type: "modular_content",
      },

      /**
       * URL (url_slug)
       */
      url: {
        name: "URL",
        codename: "url",
        id: "7825cd16-7ea1-43cd-b577-0dd9fec19172",
        externalId: undefined,
        required: false,
        type: "url_slug",
      },
    },
  },

  /**
   * Action
   */
  action: {
    name: "Action",
    codename: "action",
    id: "1972fc58-cecf-460b-b1f9-7ee65b39f791",
    externalId: undefined,
    elements: {
      /**
       * Label (text)
       */
      reference__label: {
        name: "Label",
        codename: "reference__label",
        id: "b6f0a566-251c-4612-867e-522059754b5a",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * Caption (text)
       */
      reference__caption: {
        name: "Caption",
        codename: "reference__caption",
        id: "e4f36321-a0f2-492c-8570-963b2490de4a",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * External URI (text)
       */
      reference__external_uri: {
        name: "External URI",
        codename: "reference__external_uri",
        id: "55a37264-7e9d-4ead-ab03-643c0a1431ad",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * Untitled linked items (modular_content)
       */
      reference__untitled_linked_items: {
        name: "Untitled linked items",
        codename: "reference__untitled_linked_items",
        id: "c0008386-9351-4e29-9211-69de00611271",
        externalId: undefined,
        required: false,
        type: "modular_content",
      },

      /**
       * Image (asset)
       */
      image: {
        name: "Image",
        codename: "image",
        id: "6dbcf471-4032-4840-a74d-f61e64244788",
        externalId: undefined,
        required: false,
        type: "asset",
      },
    },
  },

  /**
   * Callout
   */
  callout: {
    name: "Callout",
    codename: "callout",
    id: "85a266be-67c4-45b3-aee2-8e377ac8dfc9",
    externalId: undefined,
    elements: {
      /**
       * Type (multiple_choice)
       */
      type: {
        name: "Type",
        codename: "type",
        id: "9289b8f3-65af-4d9f-b8b8-82b89719900f",
        externalId: undefined,
        required: false,
        type: "multiple_choice",
        options: {
          /**
           * Warning
           */
          warning: {
            name: "Warning",
            id: "2fa48e0a-e9a3-4ec1-b9b2-e346c3fd16f3",
            codename: "warning",
            externalId: undefined,
          },

          /**
           * Info
           */
          info: {
            name: "Info",
            id: "e7f2cad7-fd1c-455a-9153-ada5f3e66287",
            codename: "info",
            externalId: undefined,
          },
        },
      },

      /**
       * Content (rich_text)
       */
      content: {
        name: "Content",
        codename: "content",
        id: "e04bc3fd-ce54-425e-8a46-81687899c675",
        externalId: undefined,
        required: false,
        type: "rich_text",
      },
    },
  },

  /**
   * Location
   */
  location: {
    name: "Location",
    codename: "location",
    id: "1dcf1292-116c-4109-9e96-17ce98797ac6",
    externalId: undefined,
    elements: {
      /**
       * Street Address (text)
       * Guidelines: Street address (1234 Some St.)
       */
      street_address: {
        name: "Street Address",
        codename: "street_address",
        id: "5999c7b3-e6b8-48e9-8cb9-47a992ac9179",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * City (text)
       * Guidelines: Name of city (i.e. Someville)
       */
      city: {
        name: "City",
        codename: "city",
        id: "117754dc-ed1a-4d28-8b1d-dfc30dc08f21",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * State/Province (text)
       * Guidelines: Name of state, province, or similar organizing unit.
       */
      state_province: {
        name: "State/Province",
        codename: "state_province",
        id: "4bc93b7f-5066-4e3c-8818-ff48cc0e7ab4",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * Zipcode (text)
       * Guidelines: Zipcode or similar postal code.
       */
      zipcode: {
        name: "Zipcode",
        codename: "zipcode",
        id: "042fab99-d7b4-49d8-af87-66ac9ea1c0a5",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * Telephone Number (text)
       * Guidelines: e.g. +1(111)-111-1111
       */
      telephone_number: {
        name: "Telephone Number",
        codename: "telephone_number",
        id: "4fd9af37-363d-4d8f-aa37-a589dec77a29",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * Directions (text)
       * Guidelines: Include a link to google maps.
       */
      directions: {
        name: "Directions",
        codename: "directions",
        id: "f6031d2e-aaf3-488f-bc9d-9556001db7be",
        externalId: undefined,
        required: false,
        type: "text",
      },
    },
  },

  /**
   * Navigation item root
   */
  web_spotlight_root: {
    name: "Navigation item root",
    codename: "web_spotlight_root",
    id: "dc3fbc13-8e0f-4f54-a719-d66aae30e622",
    externalId: undefined,
    elements: {
      /**
       * Title (text)
       */
      title: {
        name: "Title",
        codename: "title",
        id: "777c0c5e-9b23-4d12-a9cf-3b692be2fea4",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * Subpages (subpages)
       */
      subpages: {
        name: "Subpages",
        codename: "subpages",
        id: "682c4b4e-152f-4678-becd-1b9706a9e3a0",
        externalId: undefined,
        required: false,
        type: "subpages",
      },

      /**
       * Content (modular_content)
       */
      content: {
        name: "Content",
        codename: "content",
        id: "65da8efc-7853-4c66-b2f0-eb4f016fb8a7",
        externalId: undefined,
        required: false,
        type: "modular_content",
      },

      /**
       * URL (url_slug)
       */
      url: {
        name: "URL",
        codename: "url",
        id: "970ed664-5646-44b3-85cf-ff2d6301abbc",
        externalId: undefined,
        required: false,
        type: "url_slug",
      },

      /**
       * Meta Keywords (text)
       */
      metadata__meta_keywords: {
        name: "Meta Keywords",
        codename: "metadata__meta_keywords",
        id: "14ee3c2a-2fe6-421e-ae0e-a8a90d84fc73",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * Meta Description (text)
       */
      metadata__meta_description: {
        name: "Meta Description",
        codename: "metadata__meta_description",
        id: "85a8a109-a411-4ec5-bb89-36f3b0d73805",
        externalId: undefined,
        required: false,
        type: "text",
      },
    },
  },

  /**
   * Band
   */
  band: {
    name: "Band",
    codename: "band",
    id: "d23949c5-622d-4bd7-a752-dcb1f991e0bf",
    externalId: undefined,
    elements: {
      /**
       * Band Name (text)
       * Guidelines: Name of the band/performing artist
       */
      band_name: {
        name: "Band Name",
        codename: "band_name",
        id: "588f6253-029e-46b9-8ef2-673f8dd74f91",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * Band Logo (asset)
       * Guidelines: Utilize the most current logo image from band/artist's press kit.
       */
      band_logo: {
        name: "Band Logo",
        codename: "band_logo",
        id: "cb31087f-f15a-48f5-9e4a-ceb72bf54bbf",
        externalId: undefined,
        required: true,
        type: "asset",
      },

      /**
       * Promotional Image (asset)
       * Guidelines: Utilize the promotional image provided from the band/artist's press kit.
       */
      promotional_image: {
        name: "Promotional Image",
        codename: "promotional_image",
        id: "8cc60164-e242-45aa-8aca-5e4b0f89f3c7",
        externalId: undefined,
        required: false,
        type: "asset",
      },

      /**
       * Band Bio (rich_text)
       * Guidelines: Use the bio provided in the band/artist's press kit. If none is provided, draft a promotional bio around three paragraphs in length.
       */
      band_bio: {
        name: "Band Bio",
        codename: "band_bio",
        id: "96f6c14f-b298-4f48-9f21-05505660b46b",
        externalId: undefined,
        required: true,
        type: "rich_text",
      },

      /**
       * Band Member (modular_content)
       * Guidelines: Include the current members of the band.
       */
      band_member: {
        name: "Band Member",
        codename: "band_member",
        id: "8c74a2a4-1e4d-48fc-a431-0cc4b38419c5",
        externalId: undefined,
        required: true,
        type: "modular_content",
      },

      /**
       * Social Media (rich_text)
       * Guidelines: Insert band/artist's social media links.
       */
      social_media: {
        name: "Social Media",
        codename: "social_media",
        id: "0d33cbb4-ab04-423a-a8b9-532602e8c80a",
        externalId: undefined,
        required: false,
        type: "rich_text",
      },

      /**
       * Band Playlist (modular_content)
       * Guidelines: Include three to five of the band/artist's songs that are most popular or otherwise representational of their body of work.
       */
      band_playlist: {
        name: "Band Playlist",
        codename: "band_playlist",
        id: "cf85fe66-1563-459e-9d05-6852e84113b2",
        externalId: undefined,
        required: true,
        type: "modular_content",
      },

      /**
       * Genre (taxonomy)
       * Guidelines: Indicate music genres most relevant to the band/artist's work (multiple genres can be selected)
       */
      band_genre: {
        name: "Genre",
        codename: "band_genre",
        id: "e2228fdc-3794-4ab0-b4da-8ec19feefaf3",
        externalId: undefined,
        required: true,
        type: "taxonomy",
      },

      /**
       * slug (url_slug)
       */
      slug: {
        name: "slug",
        codename: "slug",
        id: "05302667-ee40-4042-99d6-7fbf451d21ef",
        externalId: undefined,
        required: false,
        type: "url_slug",
      },
    },
  },

  /**
   * Person
   */
  person: {
    name: "Person",
    codename: "person",
    id: "8f8faf57-cd92-4d1b-a2ae-245731c6cb06",
    externalId: undefined,
    elements: {
      /**
       * First Name (text)
       * Guidelines: First name of the person
       */
      first_name: {
        name: "First Name",
        codename: "first_name",
        id: "35cce80f-b41e-4bd0-9419-ae90a3d6d747",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * Last Name (text)
       * Guidelines: Last name of the person
       */
      last_name: {
        name: "Last Name",
        codename: "last_name",
        id: "913b4b67-421f-46dc-ae85-0962a62f4bce",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * Vocation (taxonomy)
       * Guidelines: Indicate whether this person is a member of a band or a concert review author.
       */
      vocation: {
        name: "Vocation",
        codename: "vocation",
        id: "72a5f527-e053-43d6-b879-86d15cf11368",
        externalId: undefined,
        required: true,
        type: "taxonomy",
      },
    },
  },

  /**
   * Concert Review
   */
  concert_review: {
    name: "Concert Review",
    codename: "concert_review",
    id: "531d8f36-e963-42e1-a9a6-5b92ba91bc24",
    externalId: undefined,
    elements: {
      /**
       * Concert (modular_content)
       * Guidelines: Link the concert being reviewed
       */
      concert: {
        name: "Concert",
        codename: "concert",
        id: "f717fc82-6a04-4a08-8b0f-037c57d59ab6",
        externalId: undefined,
        required: true,
        type: "modular_content",
      },

      /**
       * Headline (text)
       * Guidelines: Write an Interesting headline for the concert review.
       */
      headline: {
        name: "Headline",
        codename: "headline",
        id: "72d7db93-dafa-4dcd-bb3a-8ae51d8c4ace",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * Author (modular_content)
       * Guidelines: Link the author of the review
       */
      author: {
        name: "Author",
        codename: "author",
        id: "185df368-f182-4b54-8f38-4bc9798ffed8",
        externalId: undefined,
        required: true,
        type: "modular_content",
      },

      /**
       * Review Body (rich_text)
       * Guidelines: Write the body of the review here
       */
      review_body: {
        name: "Review Body",
        codename: "review_body",
        id: "698ed1ca-19ce-47eb-9020-c8d7ba5ee93c",
        externalId: undefined,
        required: true,
        type: "rich_text",
      },

      /**
       * Untitled url slug (url_slug)
       */
      untitled_url_slug: {
        name: "Untitled url slug",
        codename: "untitled_url_slug",
        id: "6266e3d2-ccd3-47e6-ad78-c0d23f95150a",
        externalId: undefined,
        required: true,
        type: "url_slug",
      },
    },
  },

  /**
   * Page
   */
  page: {
    name: "Page",
    codename: "page",
    id: "65f2bc97-1326-4c1f-90b5-ebce7c843dcf",
    externalId: undefined,
    elements: {
      /**
       * Title (text)
       */
      title: {
        name: "Title",
        codename: "title",
        id: "afa920e0-048e-409c-a8a0-ea5dab991089",
        externalId: undefined,
        required: false,
        type: "text",
      },

      /**
       * URL (url_slug)
       */
      url: {
        name: "URL",
        codename: "url",
        id: "f53a7593-b475-4b47-9a27-a79ba25ec4d4",
        externalId: undefined,
        required: false,
        type: "url_slug",
      },

      /**
       * Show in navigation (multiple_choice)
       */
      show_in_navigation: {
        name: "Show in navigation",
        codename: "show_in_navigation",
        id: "133493d1-38fc-42b2-b02e-6542fe507857",
        externalId: undefined,
        required: false,
        type: "multiple_choice",
        options: {
          /**
           * Yes
           */
          yes: {
            name: "Yes",
            id: "65e0ed63-f3f6-4940-a766-8fbee61abae9",
            codename: "yes",
            externalId: undefined,
          },

          /**
           * No
           */
          no: {
            name: "No",
            id: "211a482c-4c9a-4ea3-a5c8-7df83b86ccf0",
            codename: "no",
            externalId: undefined,
          },
        },
      },

      /**
       * Subpages (subpages)
       */
      subpages: {
        name: "Subpages",
        codename: "subpages",
        id: "00c4e3f8-6dd7-4d95-9531-1a61c5d901de",
        externalId: undefined,
        required: false,
        type: "subpages",
      },

      /**
       * Content (modular_content)
       */
      content: {
        name: "Content",
        codename: "content",
        id: "cd43c88e-e0ab-4b21-aedf-9793800b2025",
        externalId: undefined,
        required: false,
        type: "modular_content",
      },
    },
  },

  /**
   * Asset
   */
  asset: {
    name: "Asset",
    codename: "asset",
    id: "7a3939e5-4b32-4568-aa11-71eb776e09e2",
    externalId: undefined,
    elements: {
      /**
       * Asset Title (text)
       * Guidelines: Use a descriptive name for the asset
       */
      asset_title: {
        name: "Asset Title",
        codename: "asset_title",
        id: "87d569dc-cb1a-4d72-a961-fb6c10b9ed77",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * Alt Text (text)
       * Guidelines: Description of what the image contains to enhance accessibility for those using screen readers.
       */
      alt_text: {
        name: "Alt Text",
        codename: "alt_text",
        id: "da575d2b-b98b-4663-86c7-8e2104fe33fe",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * Asset file (asset)
       */
      asset_file: {
        name: "Asset file",
        codename: "asset_file",
        id: "4ca7db7c-ca11-4825-9127-61762a2a79ef",
        externalId: undefined,
        required: true,
        type: "asset",
      },

      /**
       * Asset Type (taxonomy)
       * Guidelines: Indicate whether the asset is a hero image or a tertiary image.
       */
      asset_type: {
        name: "Asset Type",
        codename: "asset_type",
        id: "a5a0a141-1507-4e49-8ad4-c866717502c5",
        externalId: undefined,
        required: true,
        type: "taxonomy",
      },
    },
  },

  /**
   * Playlist Song
   */
  playlist_song: {
    name: "Playlist Song",
    codename: "playlist_song",
    id: "57460815-6e85-43cf-a5d0-beed1cd3838a",
    externalId: undefined,
    elements: {
      /**
       * Song Title (text)
       * Guidelines: Title of the song.
       */
      song_title: {
        name: "Song Title",
        codename: "song_title",
        id: "6109c742-03ab-4f64-877e-8c5570c0e3a2",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * Artist Name (text)
       * Guidelines: Include the name of the artist
       */
      artist_name: {
        name: "Artist Name",
        codename: "artist_name",
        id: "32f81b2d-a827-435c-b94f-067a6af3ca2d",
        externalId: undefined,
        required: true,
        type: "text",
      },

      /**
       * Song Link (text)
       * Guidelines: Link to the song url (i.e. youtube, etc.)
       */
      song_link: {
        name: "Song Link",
        codename: "song_link",
        id: "5636bbde-0d01-498e-8c1c-dffef0405980",
        externalId: undefined,
        required: true,
        type: "text",
      },
    },
  },
} as const;
