
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

export const customApps = {
  /**
   * Model Visualizer
   */
  modelVisualizer: {
    name: "Model Visualizer",
    codename: "model_visualizer",
    sourceUrl: "https://ornate-creponne-e63a14.netlify.app/",
  },
} as const;
