/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

export const languages = {
  /**
   * Default project language
   */
  default: {
    name: "Default project language",
    codename: "default",
    id: "00000000-0000-0000-0000-000000000000",
    isActive: true,
    isDefault: true,
    fallbackLanguageId: "00000000-0000-0000-0000-000000000000",
    externalId: undefined,
  },

  /**
   * zh_Hant
   */
  zhHant: {
    name: "zh_Hant",
    codename: "zh_Hant",
    id: "743dbe2d-ff77-4745-899c-dfd954973b08",
    isActive: true,
    isDefault: false,
    fallbackLanguageId: "00000000-0000-0000-0000-000000000000",
    externalId: undefined,
  },

  /**
   * Chinese (Traditional)
   */
  chineseTraditional: {
    name: "Chinese (Traditional)",
    codename: "Chinese_(Traditional)",
    id: "b151fac6-2831-44bd-b8cf-fbfef0b67abd",
    isActive: false,
    isDefault: false,
    fallbackLanguageId: "00000000-0000-0000-0000-000000000000",
    externalId: undefined,
  },

  /**
   * zh_cn
   */
  zhCn: {
    name: "zh_cn",
    codename: "zh_cn",
    id: "527ffbfe-f579-42af-8210-f3f607f542f0",
    isActive: false,
    isDefault: false,
    fallbackLanguageId: "00000000-0000-0000-0000-000000000000",
    externalId: undefined,
  },

  /**
   * Austrailian
   */
  austrailian: {
    name: "Austrailian",
    codename: "Austrailian",
    id: "6760a660-4a47-4488-b3f0-fe57db2f582e",
    isActive: false,
    isDefault: false,
    fallbackLanguageId: "00000000-0000-0000-0000-000000000000",
    externalId: undefined,
  },
} as const;
