
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

export const previewUrls = {
  /**
   * Preview configuration
   */
  spaceDomains: {
    concert_finder: {
      spaceName: "concert finder",
      spaceCodename: "concert_finder",
      domain: "concert-finder-kn8s.vercel.app",
    },
  },
  previewUrlPatterns: {
    band: {
      contentTypeName: "Band",
      contentTypeCodename: "band",
      urlPatterns: {
        default: {
          spaceName: undefined,
          spaceCodename: undefined,
          url: "https://{Space}/c1ad4901-f748-000b-2b83-2c4fa51e2983/api/preview?secret=mySuperSecret&slug={URLslug}&type=band",
        },
      },
    },

    concert: {
      contentTypeName: "Concert",
      contentTypeCodename: "concert",
      urlPatterns: {
        default: {
          spaceName: undefined,
          spaceCodename: undefined,
          url: "https://{Space}/{Codename}",
        },
      },
    },

    concert_review: {
      contentTypeName: "Concert Review",
      contentTypeCodename: "concert_review",
      urlPatterns: {
        default: {
          spaceName: undefined,
          spaceCodename: undefined,
          url: "https://{Space}/{ItemId}",
        },
      },
    },

    navigation_item: {
      contentTypeName: "Navigation item",
      contentTypeCodename: "navigation_item",
      urlPatterns: {
        default: {
          spaceName: undefined,
          spaceCodename: undefined,
          url: "https://{Space}/{ItemId}",
        },
      },
    },

    web_spotlight_root: {
      contentTypeName: "Navigation item root",
      contentTypeCodename: "web_spotlight_root",
      urlPatterns: {
        default: {
          spaceName: undefined,
          spaceCodename: undefined,
          url: "https://{space}",
        },
      },
    },

    page: {
      contentTypeName: "Page",
      contentTypeCodename: "page",
      urlPatterns: {
        default: {
          spaceName: undefined,
          spaceCodename: undefined,
          url: "https://{Space}/{URLslug}",
        },
      },
    },

    person: {
      contentTypeName: "Person",
      contentTypeCodename: "person",
      urlPatterns: {
        default: {
          spaceName: undefined,
          spaceCodename: undefined,
          url: "https://{Space}/{ItemId}",
        },
      },
    },

    playlist_song: {
      contentTypeName: "Playlist Song",
      contentTypeCodename: "playlist_song",
      urlPatterns: {
        default: {
          spaceName: undefined,
          spaceCodename: undefined,
          url: "https://{Space}/{ItemId}",
        },
      },
    },

    venue: {
      contentTypeName: "Venue",
      contentTypeCodename: "venue",
      urlPatterns: {
        default: {
          spaceName: undefined,
          spaceCodename: undefined,
          url: "https://{space}{Lang}/venue/{URLslug}?token=amfie38djrkz9rkaj39f83k5os8vj4msksi4kfs8sjrtkwqetr",
        },
      },
    },

    content_chunk: {
      contentTypeName: "Content Chunk",
      contentTypeCodename: "content_chunk",
      urlPatterns: {
        default: {
          spaceName: undefined,
          spaceCodename: undefined,
          url: "https://{Space}/{ItemId}",
        },
      },
    },

    asset: {
      contentTypeName: "Asset",
      contentTypeCodename: "asset",
      urlPatterns: {
        default: {
          spaceName: undefined,
          spaceCodename: undefined,
          url: "https://{Space}/{ItemId}",
        },
      },
    },

    location: {
      contentTypeName: "Location",
      contentTypeCodename: "location",
      urlPatterns: {
        default: {
          spaceName: undefined,
          spaceCodename: undefined,
          url: "https://{Space}/{ItemId}",
        },
      },
    },
  },
} as const;
