
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

export const roles = {
  /**
   * Entity Editor
   */
  entityEditor: {
    name: "Entity Editor",
    codename: undefined,
    id: "2d8a3246-1b70-4937-9a09-39609f03822c",
  },

  /**
   * Site Editor
   */
  siteEditor: {
    name: "Site Editor",
    codename: undefined,
    id: "699c800c-93f3-4617-bc15-abf4931c139b",
  },

  /**
   * Project manager
   */
  projectManager: {
    name: "Project manager",
    codename: "project-manager",
    id: "cac6c839-94f5-49cd-bfd6-d573c15b7814",
  },

  /**
   * Concert Reviewer
   */
  concertReviewer: {
    name: "Concert Reviewer",
    codename: undefined,
    id: "ad86a48f-e244-45f2-8b5e-de24bd763fef",
  },
} as const;
