
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

export const spaces = {
  /**
   * concert finder
   */
  concertFinder: {
    name: "concert finder",
    codename: "concert_finder",
    id: "893edb90-6596-43c3-a94d-bf8195b54348",
  },
} as const;
