
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

export const taxonomies = {
  /**
   * year
   */
  year: {
    name: "Year",
    codename: "year",
    externalId: undefined,
    id: "58b7a826-77e3-45dc-988e-4b7ce9b54da3",
    terms: {
      /**
       * 2024
       */
      n2024: {
        name: "2024",
        codename: "n2024",
        id: "faaf4026-a8d6-483a-ae79-16fb7af2a0fe",
        externalId: undefined,
        terms: {},
      },

      /**
       * 2025
       */
      n2025: {
        name: "2025",
        codename: "n2025",
        id: "f002c8fd-8a1b-4f03-a619-0801fb2f81ef",
        externalId: undefined,
        terms: {},
      },

      /**
       * 2026
       */
      n2026: {
        name: "2026",
        codename: "n2026",
        id: "a2bfbc44-f1fa-48f1-96d4-ced707b70045",
        externalId: undefined,
        terms: {},
      },
    },
  },

  /**
   * asset_type
   */
  asset_type: {
    name: "Asset Type",
    codename: "asset_type",
    externalId: undefined,
    id: "b256f5a2-aeba-452b-8bca-adee9bf0891c",
    terms: {
      /**
       * Hero Image
       */
      hero_image: {
        name: "Hero Image",
        codename: "hero_image",
        id: "67ebf1d4-0b8d-486f-9418-37a9889de8d3",
        externalId: undefined,
        terms: {},
      },

      /**
       * Secondary Image
       */
      secondary_image: {
        name: "Secondary Image",
        codename: "secondary_image",
        id: "54a91814-fe2b-438f-997a-0ccb15269722",
        externalId: undefined,
        terms: {},
      },
    },
  },

  /**
   * importance
   */
  importance: {
    name: "Importance",
    codename: "importance",
    externalId: undefined,
    id: "247e5720-8692-4eb2-839e-68b9de7cb059",
    terms: {
      /**
       * Default
       */
      default: {
        name: "Default",
        codename: "default",
        id: "002f7ffa-ad3d-49df-a5a1-111fa85305cf",
        externalId: undefined,
        terms: {},
      },

      /**
       * Important
       */
      important: {
        name: "Important",
        codename: "important",
        id: "f291524e-f248-4d57-960c-1f5e05d424e7",
        externalId: undefined,
        terms: {},
      },

      /**
       * Trivial
       */
      trivial: {
        name: "Trivial",
        codename: "trivial",
        id: "611ce5b5-736f-4d8c-844b-5ce5482da7f6",
        externalId: undefined,
        terms: {},
      },
    },
  },

  /**
   * vocation
   */
  vocation: {
    name: "Vocation",
    codename: "vocation",
    externalId: undefined,
    id: "c2cd0726-d077-400e-be08-7621061d6107",
    terms: {
      /**
       * Band Member
       */
      band_member: {
        name: "Band Member",
        codename: "band_member",
        id: "8a13d826-043d-4909-8df5-2b773724e002",
        externalId: undefined,
        terms: {},
      },

      /**
       * Author
       */
      author: {
        name: "Author",
        codename: "author",
        id: "8ad0c7ce-7aeb-4a97-8f78-26a796857298",
        externalId: undefined,
        terms: {},
      },
    },
  },

  /**
   * genre
   */
  genre: {
    name: "Genre",
    codename: "genre",
    externalId: undefined,
    id: "a058d83a-5c5d-4290-9fcc-7a38786cefa9",
    terms: {
      /**
       * Metal
       */
      metal: {
        name: "Metal",
        codename: "metal",
        id: "e05d263b-462c-4790-9623-5517afa01459",
        externalId: undefined,
        terms: {},
      },

      /**
       * Rock
       */
      rock: {
        name: "Rock",
        codename: "rock",
        id: "22f2523d-5898-4272-8739-87933029dd1a",
        externalId: undefined,
        terms: {},
      },

      /**
       * Pop
       */
      pop: {
        name: "Pop",
        codename: "pop",
        id: "d0ab7805-a1d6-476e-aa97-cc5a6919aee3",
        externalId: undefined,
        terms: {},
      },

      /**
       * Hip Hop
       */
      hip_hop: {
        name: "Hip Hop",
        codename: "hip_hop",
        id: "6fadef75-3f08-4213-ad1a-83cd76937f0e",
        externalId: undefined,
        terms: {},
      },

      /**
       * Folk
       */
      folk: {
        name: "Folk",
        codename: "folk",
        id: "d4f930a5-7e7f-47c3-b550-e275881fab35",
        externalId: undefined,
        terms: {},
      },

      /**
       * Experimental
       */
      experimental: {
        name: "Experimental",
        codename: "experimental",
        id: "069ea7cc-1d44-4d55-87d4-54d27978861c",
        externalId: undefined,
        terms: {},
      },

      /**
       * Jazz
       */
      jazz: {
        name: "Jazz",
        codename: "jazz",
        id: "085803e6-5627-4bad-be8e-620747e3a20c",
        externalId: undefined,
        terms: {},
      },

      /**
       * All
       */
      all: {
        name: "All",
        codename: "all",
        id: "3a08c860-e7a7-4755-b58d-4965325fc4c3",
        externalId: undefined,
        terms: {},
      },
    },
  },

  /**
   * month
   */
  month: {
    name: "Month",
    codename: "month",
    externalId: undefined,
    id: "61f04fdf-d0d6-4277-a94c-0cc68a740e08",
    terms: {
      /**
       * January
       */
      january: {
        name: "January",
        codename: "january",
        id: "f92c82df-951d-4d24-b817-abf2985d2d81",
        externalId: undefined,
        terms: {},
      },

      /**
       * February
       */
      february: {
        name: "February",
        codename: "february",
        id: "380448f2-0955-4783-9725-1403efe6581e",
        externalId: undefined,
        terms: {},
      },

      /**
       * March
       */
      march: {
        name: "March",
        codename: "march",
        id: "d580c52f-8f84-4643-be4d-53ab2567950a",
        externalId: undefined,
        terms: {},
      },

      /**
       * April
       */
      april: {
        name: "April",
        codename: "april",
        id: "b0087726-6896-4960-bdbd-78dcc0a4e69a",
        externalId: undefined,
        terms: {},
      },

      /**
       * May
       */
      may: {
        name: "May",
        codename: "may",
        id: "dfa0633a-bc00-4c69-8b2b-beb65b1cc440",
        externalId: undefined,
        terms: {},
      },

      /**
       * June
       */
      june: {
        name: "June",
        codename: "june",
        id: "4b2c3b41-992c-45ed-ae66-400520208c5c",
        externalId: undefined,
        terms: {},
      },

      /**
       * July
       */
      july: {
        name: "July",
        codename: "july",
        id: "63c062d9-62d0-4077-b61f-3d6829e33ae2",
        externalId: undefined,
        terms: {},
      },

      /**
       * August
       */
      august: {
        name: "August",
        codename: "august",
        id: "2c7ed16b-9403-41e0-9945-b0b18b08baca",
        externalId: undefined,
        terms: {},
      },

      /**
       * September
       */
      september: {
        name: "September",
        codename: "september",
        id: "f819a7d1-56e6-4159-9eea-6768bf06c585",
        externalId: undefined,
        terms: {},
      },

      /**
       * October
       */
      october: {
        name: "October",
        codename: "october",
        id: "21ba8c65-588b-411b-af05-9b3ad3a0d48e",
        externalId: undefined,
        terms: {},
      },

      /**
       * November
       */
      november: {
        name: "November",
        codename: "november",
        id: "35ba4fbf-668c-4af6-9ccb-d31076b52ecb",
        externalId: undefined,
        terms: {},
      },

      /**
       * December
       */
      december: {
        name: "December",
        codename: "december",
        id: "e1a64818-bf7d-42a7-b126-665656991b60",
        externalId: undefined,
        terms: {},
      },
    },
  },
} as const;
