
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

export const webhooks = {
  /**
   * test
   */
  test: {
    name: "test",
    url: "https://webhook.site/86e02a45-9f6b-4004-9e10-bbfed5edf06e",
    id: "cc0726b3-0607-47e7-8ec5-3d56ee6183c2",
  },
} as const;
