
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

export const workflows = {
  /**
   * Default
   */
  default: {
    name: "Default",
    codename: "default",
    id: "00000000-0000-0000-0000-000000000000",
    steps: {
      draft: {
        name: "Draft",
        codename: "draft",
        id: "eee6db3b-545a-4785-8e86-e3772c8756f9",
      },
      scheduled: {
        name: "Scheduled",
        codename: "scheduled",
        id: "9d2b0228-4d0d-4c23-8b49-01a698857709",
      },
      published: {
        name: "Published",
        codename: "published",
        id: "c199950d-99f0-4983-b711-6c4c91624b22",
      },
      archived: {
        name: "Archived",
        codename: "archived",
        id: "7a535a69-ad34-47f8-806a-def1fdf4d391",
      },
    },
  },
} as const;
