
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Reference } from "../content-type-snippets/index.ts";

/**
 * Action
 *
 * Id: 1972fc58-cecf-460b-b1f9-7ee65b39f791
 * Codename: action
 */
export type Action = CoreContentType<
  ActionElementCodenames,
  {
    /**
     * Image
     *
     * Type: asset
     * Required: false
     * Codename: image
     * Id: 6dbcf471-4032-4840-a74d-f61e64244788
     */
    readonly image: Elements.AssetsElement;
  } & Reference,
  "action"
>;

/**
 * Type representing all available element codenames for Action
 */
export type ActionElementCodenames =
  | "reference__label"
  | "reference__caption"
  | "reference__external_uri"
  | "reference__untitled_linked_items"
  | "image";

/**
 * Type guard for Action
 *
 * Id: 1972fc58-cecf-460b-b1f9-7ee65b39f791
 * Codename: action
 */
export function isAction(
  item: CoreContentType | undefined | null,
): item is Action {
  return item?.system?.type === "action";
}
