
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { AssetType } from "../taxonomies/index.ts";
import type { CoreContentType } from "../system/index.ts";

/**
 * Asset
 *
 * Id: 7a3939e5-4b32-4568-aa11-71eb776e09e2
 * Codename: asset
 */
export type Asset = CoreContentType<
  AssetElementCodenames,
  {
    /**
     * Asset Title
     *
     * Type: text
     * Required: true
     * Codename: asset_title
     * Id: 87d569dc-cb1a-4d72-a961-fb6c10b9ed77
     * Guidelines: Use a descriptive name for the asset
     */
    readonly asset_title: Elements.TextElement;
    /**
     * Alt Text
     *
     * Type: text
     * Required: true
     * Codename: alt_text
     * Id: da575d2b-b98b-4663-86c7-8e2104fe33fe
     * Guidelines: Description of what the image contains to enhance accessibility for those using screen readers.
     */
    readonly alt_text: Elements.TextElement;
    /**
     * Asset file
     *
     * Type: asset
     * Required: true
     * Codename: asset_file
     * Id: 4ca7db7c-ca11-4825-9127-61762a2a79ef
     */
    readonly asset_file: Elements.AssetsElement;
    /**
     * Asset Type
     *
     * Type: taxonomy
     * Required: true
     * Codename: asset_type
     * Id: a5a0a141-1507-4e49-8ad4-c866717502c5
     * Guidelines: Indicate whether the asset is a hero image or a tertiary image.
     */
    readonly asset_type: Elements.TaxonomyElement<AssetType, "asset_type">;
  },
  "asset"
>;

/**
 * Type representing all available element codenames for Asset
 */
export type AssetElementCodenames =
  | "asset_title"
  | "alt_text"
  | "asset_file"
  | "asset_type";

/**
 * Type guard for Asset
 *
 * Id: 7a3939e5-4b32-4568-aa11-71eb776e09e2
 * Codename: asset
 */
export function isAsset(
  item: CoreContentType | undefined | null,
): item is Asset {
  return item?.system?.type === "asset";
}
