
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Callout
 *
 * Id: 85a266be-67c4-45b3-aee2-8e377ac8dfc9
 * Codename: callout
 */
export type Callout = CoreContentType<
  CalloutElementCodenames,
  {
    /**
     * Type
     *
     * Type: multiple_choice
     * Required: false
     * Codename: type
     * Id: 9289b8f3-65af-4d9f-b8b8-82b89719900f
     */
    readonly type: Elements.MultipleChoiceElement<"warning" | "info">;
    /**
     * Content
     *
     * Type: rich_text
     * Required: false
     * Codename: content
     * Id: e04bc3fd-ce54-425e-8a46-81687899c675
     */
    readonly content: Elements.RichTextElement<CoreContentType>;
  },
  "callout"
>;

/**
 * Type representing all available element codenames for Callout
 */
export type CalloutElementCodenames = "type" | "content";

/**
 * Type guard for Callout
 *
 * Id: 85a266be-67c4-45b3-aee2-8e377ac8dfc9
 * Codename: callout
 */
export function isCallout(
  item: CoreContentType | undefined | null,
): item is Callout {
  return item?.system?.type === "callout";
}
