
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Content Chunk
 *
 * Id: a797ce49-151e-4ecf-a12c-2a34ef9cd750
 * Codename: content_chunk
 */
export type ContentChunk = CoreContentType<
  ContentChunkElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: true
     * Codename: title
     * Id: 3cf97a75-0941-4bba-ac68-ebbb50fe3ebb
     */
    readonly title: Elements.TextElement;
    /**
     * Content
     *
     * Type: rich_text
     * Required: true
     * Codename: content
     * Id: 3bc4388e-c65f-4e2f-836a-aa5e55b1a350
     */
    readonly content: Elements.RichTextElement<CoreContentType>;
  },
  "content_chunk"
>;

/**
 * Type representing all available element codenames for Content Chunk
 */
export type ContentChunkElementCodenames = "title" | "content";

/**
 * Type guard for Content Chunk
 *
 * Id: a797ce49-151e-4ecf-a12c-2a34ef9cd750
 * Codename: content_chunk
 */
export function isContentChunk(
  item: CoreContentType | undefined | null,
): item is ContentChunk {
  return item?.system?.type === "content_chunk";
}
