
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Navigation item
 *
 * Id: aab37be7-07b8-458a-afe5-855ec464c05a
 * Codename: navigation_item
 */
export type NavigationItem = CoreContentType<
  NavigationItemElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: false
     * Codename: title
     * Id: 58147925-9553-4e01-a7a8-ce709482a952
     */
    readonly title: Elements.TextElement;
    /**
     * Subpages
     *
     * Type: subpages
     * Required: false
     * Codename: subpages
     * Id: 05359978-9d45-4677-b632-3ca2ac41200d
     */
    readonly subpages: Elements.LinkedItemsElement<CoreContentType>;
    /**
     * Content
     *
     * Type: modular_content
     * Required: false
     * Codename: content
     * Id: 600225f9-6560-47fd-8b81-1b004ef0da88
     */
    readonly content: Elements.LinkedItemsElement<CoreContentType>;
    /**
     * URL
     *
     * Type: url_slug
     * Required: false
     * Codename: url
     * Id: 7825cd16-7ea1-43cd-b577-0dd9fec19172
     */
    readonly url: Elements.UrlSlugElement;
  },
  "navigation_item"
>;

/**
 * Type representing all available element codenames for Navigation item
 */
export type NavigationItemElementCodenames =
  | "title"
  | "subpages"
  | "content"
  | "url";

/**
 * Type guard for Navigation item
 *
 * Id: aab37be7-07b8-458a-afe5-855ec464c05a
 * Codename: navigation_item
 */
export function isNavigationItem(
  item: CoreContentType | undefined | null,
): item is NavigationItem {
  return item?.system?.type === "navigation_item";
}
