
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Metadata } from "../content-type-snippets/index.ts";
import type { Page } from "./index.ts";

/**
 * Navigation item root
 *
 * Id: dc3fbc13-8e0f-4f54-a719-d66aae30e622
 * Codename: web_spotlight_root
 */
export type NavigationItemRoot = CoreContentType<
  NavigationItemRootElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: false
     * Codename: title
     * Id: 777c0c5e-9b23-4d12-a9cf-3b692be2fea4
     */
    readonly title: Elements.TextElement;
    /**
     * Subpages
     *
     * Type: subpages
     * Required: false
     * Codename: subpages
     * Id: 682c4b4e-152f-4678-becd-1b9706a9e3a0
     */
    readonly subpages: Elements.LinkedItemsElement<Page>;
    /**
     * Content
     *
     * Type: modular_content
     * Required: false
     * Codename: content
     * Id: 65da8efc-7853-4c66-b2f0-eb4f016fb8a7
     */
    readonly content: Elements.LinkedItemsElement<CoreContentType>;
    /**
     * URL
     *
     * Type: url_slug
     * Required: false
     * Codename: url
     * Id: 970ed664-5646-44b3-85cf-ff2d6301abbc
     */
    readonly url: Elements.UrlSlugElement;
  } & Metadata,
  "web_spotlight_root"
>;

/**
 * Type representing all available element codenames for Navigation item root
 */
export type NavigationItemRootElementCodenames =
  | "title"
  | "subpages"
  | "content"
  | "url"
  | "metadata__meta_keywords"
  | "metadata__meta_description";

/**
 * Type guard for Navigation item root
 *
 * Id: dc3fbc13-8e0f-4f54-a719-d66aae30e622
 * Codename: web_spotlight_root
 */
export function isNavigationItemRoot(
  item: CoreContentType | undefined | null,
): item is NavigationItemRoot {
  return item?.system?.type === "web_spotlight_root";
}
