
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Concerts
* Environment: Production
* Id: c1ad4901-f748-000b-2b83-2c4fa51e2983
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Page
 *
 * Id: 65f2bc97-1326-4c1f-90b5-ebce7c843dcf
 * Codename: page
 */
export type Page = CoreContentType<
  PageElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: false
     * Codename: title
     * Id: afa920e0-048e-409c-a8a0-ea5dab991089
     */
    readonly title: Elements.TextElement;
    /**
     * URL
     *
     * Type: url_slug
     * Required: false
     * Codename: url
     * Id: f53a7593-b475-4b47-9a27-a79ba25ec4d4
     */
    readonly url: Elements.UrlSlugElement;
    /**
     * Show in navigation
     *
     * Type: multiple_choice
     * Required: false
     * Codename: show_in_navigation
     * Id: 133493d1-38fc-42b2-b02e-6542fe507857
     */
    readonly show_in_navigation: Elements.MultipleChoiceElement<"yes" | "no">;
    /**
     * Subpages
     *
     * Type: subpages
     * Required: false
     * Codename: subpages
     * Id: 00c4e3f8-6dd7-4d95-9531-1a61c5d901de
     */
    readonly subpages: Elements.LinkedItemsElement<CoreContentType>;
    /**
     * Content
     *
     * Type: modular_content
     * Required: false
     * Codename: content
     * Id: cd43c88e-e0ab-4b21-aedf-9793800b2025
     */
    readonly content: Elements.LinkedItemsElement<CoreContentType>;
  },
  "page"
>;

/**
 * Type representing all available element codenames for Page
 */
export type PageElementCodenames =
  | "title"
  | "url"
  | "show_in_navigation"
  | "subpages"
  | "content";

/**
 * Type guard for Page
 *
 * Id: 65f2bc97-1326-4c1f-90b5-ebce7c843dcf
 * Codename: page
 */
export function isPage(item: CoreContentType | undefined | null): item is Page {
  return item?.system?.type === "page";
}
